version: 0.2

phases:
  install: 
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam --version
      - echo $SAM_BUCKET
      - ls -ltra ./*/*
      - sam validate
      - sam build --bedug
      - sam package --s3-bucket $SAM_BUCKET --template-file template.yaml --output-template-file packaged.yaml
      - cat packaged.yaml

artifacts:
  files:
    - template.yaml
    - packaged.yaml
