AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  socketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
        Name: !Sub 
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.action"

  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
         ApiId: !Ref socketAPI
         IntegrationType: AWS_PROXY
         CredentialsArn: 'arn:aws:iam::387507663773:role/core-lambda-roles'
         IntegrationUri: !Sub 
          - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambdaARN}/invocations"
          - ConnectLambdaARN: !GetAtt ConnectLambda.Arn
  
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
         RouteKey: $connect
         ApiId: !Ref socketAPI
         OperationName: ConnectRoute
         Target: !Sub "integrations/${ConnectInteg}"

  ConnectLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'connect-lambda'
      CodeUri: lambdas/connect_lambda/
      Role: 'arn:aws:iam::387507663773:role/core-lambda-roles'
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Timeout: 600

  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
         - socketAPI
    Properties:
      FunctionName: !Ref ConnectLambda
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceAccount: !Sub '${AWS::AccountId}'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS:AccountId}:${socketAPI}/*/$connect'

  StreamingOpenai:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'streaming-openai'
      CodeUri: lambdas/streaming_lambda/
      Role: 'arn:aws:iam::387507663773:role/core-lambda-roles'
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 600
  
  OpenaiInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
         ApiId: !Ref socketAPI
         IntegrationType: AWS_PROXY
         CredentialsArn: 'arn:aws:iam::387507663773:role/core-lambda-roles'
         IntegrationUri: !Sub 
          - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambdaARN}/invocations"
          - ConnectLambdaARN: !GetAtt StreamingOpenai.Arn
  
  OpenaiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
         RouteKey: openai
         ApiId: !Ref socketAPI
         OperationName: OpenaiRoute
         Target: !Sub "integrations/${OpenaiInteg}"

  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
         - socketAPI
    Properties:
      FunctionName: !Ref StreamingOpenai
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceAccount: !Sub '${AWS::AccountId}'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS:AccountId}:${socketAPI}/*/openai'



Outputs:
  socketAPI:
    Description: URL for the API Gateway
    Value: !Ref socketAPI